spring:
  datasource:
    username: root
    hikari:
      password: root1120
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver